[env:esp32doit-devkit-v1]
platform     = espressif32
board        = esp32doit-devkit-v1
framework    = arduino
monitor_speed = 115200
lib_deps     =
    sparkfun/SparkFun Qwiic Scale NAU7802 Arduino Library@^1.0.6

[env:native]
platform     = native
test_framework = googletest
lib_deps     =
    rapidcheck/rapidcheck
