[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/7semi-solutions/7Semi-NAU7802-24bit-ADC-for-Weight-Scale.git
